# Generated by Django 4.2.13 on 2024-05-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=10, unique=True)),
                ('buy_value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('sell_value', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
