# Generated by Django 4.2.13 on 2024-06-08 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_user'),
        ('users', '0002_customuser_is_mfa_enabled_customuser_otp_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to='wallets.wallet'),
        ),
    ]
